### ISSUE TITLE
Release zips are twice as big as they should be

### ISSUE THREAD

**Issue by xross** [xmos/sw_usb_audio#193]
Release zips; 300mb, unzipped: 160mb

Windows warns multiple files (50) have been added twice.  

These are generated by a release script. Seems to be an issue after v7.0.0

**Comment by xross** [comment]
![MicrosoftTeams-image (15)](https://github.com/xmos/sw_usb_audio/assets/642910/7dfb2ac5-f1dc-4ced-bcba-50de75eac770)

**Comment by xross** [comment]
All duplicated files appear to be xe files.

**Comment by VergilWang15** [comment]
Yes, I encountered the same issue today. When I was extracting files, Windows prompted me whether I wanted to overwrite the files with duplicate names.

**Comment by xross** [comment]
This has been resolved in the current release script. As of v8.0.0 release this should no longer be an issue.
