### ISSUE TITLE
192KHz device, 16channel device doesn't enumerate on Windows when bcdUSB is set to 2.01 

### ISSUE THREAD

**Issue by shuchitak** [xmos/sw_usb_audio#253]
If the bcdUSB version in the device descriptor is set to 2.01 (to implement the BOS descriptor), build configurations with max_freq 192KHz and interfaces having num_chans > 10 (for example, 2AMi16o16xxxaax), that were previously enumerating, stop enumerating on Windows. 
The Beagle trace shows the host querying for the device descriptors, followed by the configuration descriptors and then just abandoning enumeration.
This happens with both the Thesycon driver and built in Windows driver.
The device enumerates fine on MacOS.

**Comment by xross** [comment]
This was resolved in lib_xua: 

CHANGED: Limit HS_STREAM_FORMAT_OUTPUT_1/2/3_MAXPACKETSIZE to 1024 bytes to fix bcdUSB version 2.01 USB device supporting a sampling rate of 192KHz not enumerating on Windows
