### ISSUE TITLE
app_usb_aud_xk_evk_xu316 fails on USB_GET_CONFIGURATION when I2S_CHANS_DAC = 0

### ISSUE THREAD

**Issue by ed-xmos** [xmos/sw_usb_audio#279]
[dac_2_fail.tdc.zip](https://github.com/user-attachments/files/17057541/dac_2_fail.tdc.zip)

Get an invalid PID sequence

You can see the usbstdrequest fails with:
#define USB_GET_CONFIGURATION           0x08

![Screenshot 2024-09-19 at 11 27 07](https://github.com/user-attachments/assets/ee4ce1ba-11e8-4f87-b5e4-ef5c63556537)

**Comment by Felipe-Rafael-Rosa** [comment]
I think this will help you.
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive

**Comment by ed-xmos** [comment]
Reporting fail by ed - I have seen the issue but not on this fw
